# Generated by Django 6.0 on 2026-01-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jupyter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JupyterPermission',
        ),
    ]
